(in-package :mcclim-render)

(declaim (optimize speed))

(defgeneric make-aa-render-draw-fn (image clip-region pixeled-design))
(defgeneric make-aa-render-draw-span-fn (image clip-region pixeled-design))
(defgeneric make-aa-render-xor-draw-fn (image clip-region pixeled-design))
(defgeneric make-aa-render-xor-draw-span-fn (image clip-region pixeled-design))

(defgeneric cells-sweep/rectangle (image design state clip-region
                                   &key foreground background))

(defmethod cells-sweep/rectangle ((image basic-image) ink state clip-region
                                  &key foreground background)
  (let ((draw-function nil)
        (draw-span-function nil)
        (rgba-design (make-pixeled-design ink :foreground foreground :background background))
        (current-clip-region
         (if (rectanglep clip-region)
             nil
             clip-region)))
    (clim:with-bounding-rectangle* (min-x min-y max-x max-y)
	clip-region
      (setf draw-function
            (if (typep ink 'standard-flipping-ink)
                (make-aa-render-xor-draw-fn image current-clip-region
                                            rgba-design)
                (make-aa-render-draw-fn image current-clip-region
                                        rgba-design)))
      (setf draw-span-function
            (if (typep ink 'standard-flipping-ink)
                (make-aa-render-xor-draw-span-fn image current-clip-region
                                                 rgba-design)
                (make-aa-render-draw-span-fn image current-clip-region
                                             rgba-design)))
      (aa:cells-sweep/rectangle state
                                (floor min-x)
                                (floor min-y)
                                (ceiling max-x)
                                (ceiling max-y)
                                draw-function
                                draw-span-function))))
;;;
;;; Image operatios
;;;
(defmacro make-make-aa-render-draw-fn (image-class)
  `(progn
     (defmethod make-aa-render-draw-fn ((image ,image-class) clip-region pixeled-design)
       (let ((pixels (image-pixels image))
             (design-fn (make-pixeled-rgba-octets-fn pixeled-design)))
         (declare (type ,(image-pixels-type image-class) pixels)
                  (type pixeled-design-fn design-fn))
         (if clip-region
             (lambda (x y alpha)
               (declare (type fixnum x y)
                        (type fixnum alpha))
               (when (clim:region-contains-position-p clip-region x y)
                 (setf alpha (min (abs alpha) 255))
                 (when (plusp alpha)
                   (multiple-value-bind (r.fg g.fg b.fg a.fg)
                       (funcall design-fn x y)
                     (if (> (octet-mult a.fg alpha) 250)
                         (multiple-value-bind (red green blue alpha)	  
                             (values r.fg g.fg b.fg 255)
                           ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))
                         (multiple-value-bind (r.bg g.bg b.bg a.bg)
                             ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                           (multiple-value-bind (red green blue alpha)
                               (octet-blend-function r.bg g.bg b.bg a.bg r.fg g.fg b.fg (octet-mult a.fg alpha))
                             ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))))))))
             (lambda (x y alpha)
               (declare (type fixnum x y)
                        (type fixnum alpha))
               (setf alpha (min (abs alpha) 255))
               (when (plusp alpha)
                 (multiple-value-bind (r.fg g.fg b.fg a.fg)
                     (funcall design-fn x y)
                   (if (> (octet-mult a.fg alpha) 250)
                       (multiple-value-bind (red green blue alpha)	  
                           (values r.fg g.fg b.fg 255)
                         ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))
                       (multiple-value-bind (r.bg g.bg b.bg a.bg)
                           ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                         (multiple-value-bind (red green blue alpha)
                             (octet-blend-function r.bg g.bg b.bg a.bg r.fg g.fg b.fg (octet-mult a.fg alpha))
                           ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))))))))))
     (defmethod make-aa-render-draw-fn ((image ,image-class) clip-region (pixeled-design pixeled-uniform-design))
       (let ((pixels (image-pixels image)))
         (declare (type ,(image-pixels-type image-class) pixels))
         (multiple-value-bind (r.fg g.fg b.fg a.fg)
             (values
              (pixeled-uniform-design-red pixeled-design)
              (pixeled-uniform-design-green pixeled-design)
              (pixeled-uniform-design-blue pixeled-design)
              (pixeled-uniform-design-alpha pixeled-design))
           (if clip-region
               (lambda (x y alpha)
                 (declare (type fixnum x y)
                          (type fixnum alpha))
                 (when (clim:region-contains-position-p clip-region x y)
                   (setf alpha (min (abs alpha) 255))
                   (when (plusp alpha)
                     (if (> (octet-mult a.fg alpha) 250)
                         (multiple-value-bind (red green blue alpha)	  
                             (values r.fg g.fg b.fg 255)
                           ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))
                         (multiple-value-bind (r.bg g.bg b.bg a.bg)
                             ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                           (multiple-value-bind (red green blue alpha)
                               (octet-blend-function r.bg g.bg b.bg a.bg r.fg g.fg b.fg (octet-mult a.fg alpha))
                             ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha)))))))
               (lambda (x y alpha)
                 (declare (type fixnum x y)
                          (type fixnum alpha))
                 (setf alpha (min (abs alpha) 255))
                 (when (plusp alpha)
                   (if (> (octet-mult a.fg alpha) 250)
                       (multiple-value-bind (red green blue alpha)	  
                           (values r.fg g.fg b.fg 255)
                         ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))
                       (multiple-value-bind (r.bg g.bg b.bg a.bg)
                           ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                         (multiple-value-bind (red green blue alpha)
                             (octet-blend-function r.bg g.bg b.bg a.bg r.fg g.fg b.fg (octet-mult a.fg alpha))
                           ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))))))))))))

(defmacro make-make-aa-render-draw-span-fn (image-class)
  `(progn
     (defmethod make-aa-render-draw-span-fn ((image ,image-class) clip-region pixeled-design)
       (let ((pixels (image-pixels image))
             (design-fn (make-pixeled-rgba-octets-fn pixeled-design)))
         (declare (type ,(image-pixels-type image-class) pixels)
                  (type pixeled-design-fn design-fn))
         (if clip-region
             (lambda (x1 x2 y alpha)
               (declare (type fixnum x1 x2 y)
                        (type fixnum alpha))
               (loop for x from x1 below x2 do
                    (when (clim:region-contains-position-p clip-region x y)
                      (setf alpha (min (abs alpha) 255))
                      (when (plusp alpha)
                        (multiple-value-bind (r.fg g.fg b.fg a.fg)
                            (funcall design-fn x y)
                          (if (> (octet-mult a.fg alpha) 250)
                              (multiple-value-bind (red green blue alpha)	  
                                  (values r.fg g.fg b.fg 255)
                                ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))
                              (multiple-value-bind (r.bg g.bg b.bg a.bg)
                                  ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                                (multiple-value-bind (red green blue alpha)
                                    (octet-blend-function r.bg g.bg b.bg a.bg r.fg g.fg b.fg (octet-mult a.fg alpha))
                                  ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha)))))))))
             (lambda (x1 x2 y alpha)
               (declare (type fixnum x1 x2 y)
                        (type fixnum alpha))
               (setf alpha (min (abs alpha) 255))
               (when (plusp alpha)
                 (loop for x from x1 below x2 do
                      (multiple-value-bind (r.fg g.fg b.fg a.fg)
                          (funcall design-fn x y)
                        (if (> (octet-mult a.fg alpha) 250)
                            (multiple-value-bind (red green blue alpha)	  
                                (values r.fg g.fg b.fg 255)
                              ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))
                            (multiple-value-bind (r.bg g.bg b.bg a.bg)
                                ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                              (multiple-value-bind (red green blue alpha)
                                  (octet-blend-function r.bg g.bg b.bg a.bg r.fg g.fg b.fg (octet-mult a.fg alpha))
                                ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha)))))))))))
     (defmethod make-aa-render-draw-span-fn ((image ,image-class) clip-region (pixeled-design pixeled-uniform-design))
       (let ((pixels (image-pixels image)))
         (declare (type ,(image-pixels-type image-class) pixels))
         (multiple-value-bind (r.fg g.fg b.fg a.fg)
             (values
              (pixeled-uniform-design-red pixeled-design)
              (pixeled-uniform-design-green pixeled-design)
              (pixeled-uniform-design-blue pixeled-design)
              (pixeled-uniform-design-alpha pixeled-design))
           (if clip-region
               (lambda (x1 x2 y alpha)
                 (declare (type fixnum x1 x2 y)
                          (type fixnum alpha))
                 (loop for x from x1 below x2 do
                      (when (clim:region-contains-position-p clip-region x y)
                        (setf alpha (min (abs alpha) 255))
                        (when (plusp alpha)
                          (if (> (octet-mult a.fg alpha) 250)
                              (multiple-value-bind (red green blue alpha)	  
                                  (values r.fg g.fg b.fg 255)
                                ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))
                              (multiple-value-bind (r.bg g.bg b.bg a.bg)
                                  ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                                (multiple-value-bind (red green blue alpha)
                                    (octet-blend-function r.bg g.bg b.bg a.bg r.fg g.fg b.fg (octet-mult a.fg alpha))
                                  ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))))))))
               (lambda (x1 x2 y alpha)
                 (declare (type fixnum x1 x2 y)
                          (type fixnum alpha))
                 (setf alpha (min (abs alpha) 255))
                 (when (plusp alpha)
                   (loop for x from x1 below x2 do
                        (if (> (octet-mult a.fg alpha) 250)
                            (multiple-value-bind (red green blue alpha)	  
                                (values r.fg g.fg b.fg 255)
                              ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))
                            (multiple-value-bind (r.bg g.bg b.bg a.bg)
                                ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                              (multiple-value-bind (red green blue alpha)
                                  (octet-blend-function r.bg g.bg b.bg a.bg r.fg g.fg b.fg (octet-mult a.fg alpha))
                                ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha)))))))))))))

(defmacro make-make-aa-render-xor-draw-fn (image-class)
  `(defmethod make-aa-render-xor-draw-fn ((image ,image-class) clip-region pixeled-design)
     (let ((pixels (image-pixels image))
           (design-fn (make-pixeled-rgba-octets-fn pixeled-design)))
       (declare (type ,(image-pixels-type image-class) pixels)
                (type pixeled-design-fn design-fn))
       (if clip-region
           (lambda (x y alpha)
             (declare (type fixnum x y)
                      (type fixnum alpha))
             (when (clim:region-contains-position-p clip-region x y)
               (setf alpha (min (abs alpha) 255))
               (when (plusp alpha)
                 (multiple-value-bind (r.fg g.fg b.fg a.fg)
                     (funcall design-fn x y)
                   (multiple-value-bind (r.bg g.bg b.bg a.bg)
                       ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                     (multiple-value-bind (red green blue alpha)	  
                         (octet-blend-function r.bg g.bg b.bg a.bg
                                               (color-octet-xor r.bg r.fg) (color-octet-xor g.bg g.fg)
                                               (color-octet-xor b.bg b.fg) (octet-mult a.fg alpha))
                       ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha)))))))
           (lambda (x y alpha)
             (declare (type fixnum x y)
                      (type fixnum alpha))
             (setf alpha (min (abs alpha) 255))
             (when (plusp alpha)
               (multiple-value-bind (r.fg g.fg b.fg a.fg)
                   (funcall design-fn x y)
                 (multiple-value-bind (r.bg g.bg b.bg a.bg)
                     ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                   (multiple-value-bind (red green blue alpha)	  
                       (octet-blend-function r.bg g.bg b.bg a.bg
                                             (color-octet-xor r.bg r.fg) (color-octet-xor g.bg g.fg)
                                             (color-octet-xor b.bg b.fg) (octet-mult a.fg alpha))
                     ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))))))))))

(defmacro make-make-aa-render-xor-draw-span-fn (image-class)
  `(defmethod make-aa-render-xor-draw-span-fn ((image ,image-class) clip-region pixeled-design)
     (let ((pixels (image-pixels image))
           (design-fn (make-pixeled-rgba-octets-fn pixeled-design)))
       (declare (type ,(image-pixels-type image-class) pixels)
                (type pixeled-design-fn design-fn))
       (if clip-region
           (lambda (x1 x2 y alpha)
             (declare (type fixnum x1 x2 y)
                      (type fixnum alpha))
             (loop for x from x1 below x2 do
                  (when (clim:region-contains-position-p clip-region x y)
                    (setf alpha (min (abs alpha) 255))
                    (when (plusp alpha)
                      (multiple-value-bind (r.fg g.fg b.fg a.fg)
                          (funcall design-fn x y)
                        (multiple-value-bind (r.bg g.bg b.bg a.bg)
                            ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                          (multiple-value-bind (red green blue alpha)	  
                              (octet-blend-function r.bg g.bg b.bg a.bg
                                                    (color-octet-xor r.bg r.fg) (color-octet-xor g.bg g.fg)
                                                    (color-octet-xor b.bg b.fg) (octet-mult a.fg alpha))
                            ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha))))))))
           (lambda (x1 x2 y alpha)
             (declare (type fixnum x1 x2 y)
                      (type fixnum alpha))
             (setf alpha (min (abs alpha) 255))
             (when (plusp alpha)
               (loop for x from x1 below x2 do
                    (multiple-value-bind (r.fg g.fg b.fg a.fg)
                        (funcall design-fn x y)
                      (multiple-value-bind (r.bg g.bg b.bg a.bg)
                          ,(make-get-rgba-octets-code image-class 'pixels 'x 'y)
                        (multiple-value-bind (red green blue alpha)	  
                            (octet-blend-function r.bg g.bg b.bg a.bg
                                                  (color-octet-xor r.bg r.fg) (color-octet-xor g.bg g.fg)
                                                  (color-octet-xor b.bg b.fg) (octet-mult a.fg alpha))
                          ,(make-set-rgba-octets-code image-class 'pixels 'x 'y 'red 'green 'blue 'alpha)))))))))))

;;;
;;; Stencil Operations
;;;

(defgeneric make-aa-render-alpha-draw-fn (image clip-region))
(defgeneric make-aa-render-alpha-draw-span-fn (image clip-region))

(defmacro make-make-aa-render-alpha-draw-fn (image-class)
  `(defmethod make-aa-render-alpha-draw-fn ((image ,image-class) clip-region)
     (let ((pixels (image-pixels image)))
       (declare (type ,(image-pixels-type image-class) pixels))
       (if clip-region
           (lambda (x y alpha)
             (declare (type fixnum x y)
                      (type fixnum alpha))
             (when (clim:region-contains-position-p clip-region x y)
               (setf alpha (min (abs alpha) 255))
               (when (plusp alpha)
                 ,(make-set-alpha-octet-code image-class 'pixels 'x 'y 'alpha))))
           (lambda (x y alpha)
             (declare (type fixnum x y)
                      (type fixnum alpha))
             (setf alpha (min (abs alpha) 255))
             (when (plusp alpha)
               ,(make-set-alpha-octet-code image-class 'pixels 'x 'y 'alpha)))))))

(defmacro make-make-aa-render-alpha-draw-span-fn (image-class)
  `(defmethod make-aa-render-alpha-draw-span-fn ((image ,image-class) clip-region)
     (let ((pixels (image-pixels image)))
       (declare (type ,(image-pixels-type image-class) pixels))
       (if clip-region
           (lambda (x1 x2 y alpha)
             (declare (type fixnum x1 x2 y)
                      (type fixnum alpha))
             (loop for x from x1 below x2 do
                  (when (clim:region-contains-position-p clip-region x y)
                    (setf alpha (min (abs alpha) 255))
                    (when (plusp alpha)
                      ,(make-set-alpha-octet-code image-class 'pixels 'x 'y 'alpha)))))
           (lambda (x1 x2 y alpha)
             (declare (type fixnum x1 x2 y)
                      (type fixnum alpha))
             (setf alpha (min (abs alpha) 255))
             (loop for x from x1 below x2 do
                  (when (plusp alpha)
                    ,(make-set-alpha-octet-code image-class 'pixels 'x 'y 'alpha))))))))



