@node [Ref] Kill Ring Protocol
@subsection Kill Ring Protocol

@menu
* Kill Ring Protocol Specification::
* Kill Ring Implementation::
@end menu

@node Kill Ring Protocol Specification
@subsubsection Kill Ring Protocol Specification

@include class-drei-kill-ring-kill-ring.texi

@include fun-drei-kill-ring-kill-ring-max-size.texi

@include fun-drei-kill-ring-kill-ring-length.texi

@include fun-drei-kill-ring-kill-ring-standard-push.texi

@include fun-drei-kill-ring-kill-ring-concatenating-push.texi

@include fun-drei-kill-ring-kill-ring-reverse-concatenating-push.texi

@include fun-drei-kill-ring-rotate-yank-position.texi

@include fun-drei-kill-ring-reset-yank-position.texi

@include fun-drei-kill-ring-kill-ring-yank.texi

@node Kill Ring Implementation
@subsubsection Kill Ring Implementation

The kill ring structure is built mainly of two parts: the stack-like
ring portion, which is a cursorchain, and the yank point, which is a
left-sticky-flexicursor.  To initialize a kill ring, the @cl{:max-size} slot
initarg is simply used to set the max size.  The remaining slots
consisting of the cursorchain and the left-sticky-flexicursor are
instantized upon creation of the kill ring.

Stored onto the cursorchain are simple-vectors of objects, mainly
characters from a Drei buffer.  In order to facilitate this, the kill
ring implementation borrows heavily from the flexichain library of
functions. The following functions lie outside the kill ring and
flexichain protocols, but are pertinent to the kill ring implementation.

@include fun-drei-kill-ring-kill-ring-chain.texi

@include fun-drei-kill-ring-kill-ring-cursor.texi
