@node Output Recording Extensions
@chapter Output Recording Extensions
@cindex extensions

@menu
* Standard classes::
@end menu

@c map-over-output-records

@node Standard classes
@section Standard classes

@deftp {Class} standard-output-recording-stream
@end deftp

This class is mixed into some other stream class to add output recording
facilities. It is not instantiable.
