(format t "Ensure you have issued the command: (require \"asdf\")...~%")
(format t "~%Loading McCLIM~%")
;;;(load "/Users/duncan/sandbox/evins/McCLIM/system")
(load "/Users/duncan/sandbox/common-lisp.net/mcclim/system")
(asdf:operate 'asdf:load-op 'clim)
(asdf:operate 'asdf:load-op 'clim-examples)
(asdf:operate 'asdf:load-op 'clim-listener)
(load "/Users/duncan/sandbox/common-lisp.net/mcclim/Apps/Inspector/clouseau.asd")
(asdf:operate 'asdf:load-op 'clouseau)
(format t "~%Done.~%")
