(format t "Ensure you have issued the command: (require \"asdf\")...~%")
(format t "~%Loading McCLIM~%")
;;;(load "/Users/duncan/sandbox/evins/McCLIM/system")
(load "/Users/duncan/sandbox/mikemac/McCLIM/system")
(asdf:operate 'asdf:load-op 'clim)
(asdf:operate 'asdf:load-op 'clim-examples)
;;;(load "/Users/duncan/sandbox/evins/McCLIM/Apps/Listener/clim-listener.asd")
(load "/Users/duncan/sandbox/mikemac/McCLIM/Apps/Listener/clim-listener.asd")
(asdf:operate 'asdf:load-op 'clim-listener)
(format t "~%Done.~%")
