@node Protocols
@section Protocols
@cindex Drei protocols
@cindex text-editor protocols
@cindex text-editor API
@cindex Drei API

Much of Drei's functionality is based on generic function
protocols. This section lists some of them.

@menu
* [Ref] Buffer Protocol::
* [Ref] Buffer Modification Protocol::
* [Ref] Syntax Protocol::
* [Ref] View Protocol::
* [Ref] Unit Protocol::
* [Ref] Redisplay Protocol::
* [Ref] Undo Protocol::
* [Ref] Kill Ring Protocol::
@end menu

@include reference/protocols/buffer.texi
@include reference/protocols/buffer-modification.texi
@include reference/protocols/syntax.texi
@include reference/protocols/view.texi
@include reference/protocols/unit.texi
@include reference/protocols/redisplay.texi
@include reference/protocols/undo.texi
@include reference/protocols/kill-ring.texi
