
\input texinfo

@setfilename drei
@settitle McCLIM Drei editor substrate Manual

@copying
Copyright @copyright{} 2004,2005,2006,2007,2008,2017 the McCLIM hackers.
@end copying

@dircategory Common Lisp
@direntry
* Drei editor substrate: (mcclim drei). Documentation and reference manual.
@end direntry

@titlepage
@title Drei Manual

@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@iftex
@contents
@end iftex

@include macros.texi

@ifnottex
@node Top
@top Drei Manual
@insertcopying
@end ifnottex

@cindex drei
@cindex input-editor
@cindex text-editor
@cindex text-field

@menu
* Explanation::                 Understanding Drei
* Reference::

@c Index
* Concept Index::
* Variable Index::
* Function And Macro Index::
@end menu

Drei - an acronym for @i{Drei Replaces EINE's Inheritor} - is one of the
editor substrates provided by McCLIM. Drei is activated by default.

@node Explanation
@chapter Explanation

@menu
* Drei Concepts::               The core Drei concepts and design philosophy.
* Drei Variants::
* Drei Commands::               Information about defining commands for Drei
* DREI-BASE Package::
* [Explanation] Buffer Protocol::
* Syntax Modules::
@end menu

@include explanation/concepts.texi
@include explanation/variants.texi
@include explanation/drei-commands.texi
@include explanation/drei-base.texi
@include explanation/buffer-protocol.texi
@include explanation/syntax-modules.texi

@node Reference
@chapter Reference

@menu
* Access Functions::
* Special Variables::
* External API::                The classes, functions and macros that make up the core of Drei
* Protocols::                   Description of protocols used by Drei.
* Drei Commands::
@end menu

@include reference/access.texi
@include reference/special.texi
@include reference/external-api.texi
@include reference/protocols.texi
@include reference/commands.texi

@node Concept Index
@unnumbered Concept Index

@printindex cp

@node Variable Index
@unnumbered Variable Index

@printindex vr

@node Function And Macro Index
@unnumbered Function And Macro Index

@printindex fn

@bye
